// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9tb0-qyW7JBF1GEOc6u6aUcwrdo77gwY',
    appId: '1:1095617289196:web:54caf6d53a49e091e83ec9',
    messagingSenderId: '1095617289196',
    projectId: 'kabal-xo5kyc',
    authDomain: 'kabal-xo5kyc.firebaseapp.com',
    storageBucket: 'kabal-xo5kyc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnRxIFCoV6fJT1PWVIH1acbkXrkTzmg6I',
    appId: '1:1095617289196:android:0e13eb5c92402220e83ec9',
    messagingSenderId: '1095617289196',
    projectId: 'kabal-xo5kyc',
    storageBucket: 'kabal-xo5kyc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9tb0-qyW7JBF1GEOc6u6aUcwrdo77gwY',
    appId: '1:1095617289196:web:6b5e5e0fc70b49ede83ec9',
    messagingSenderId: '1095617289196',
    projectId: 'kabal-xo5kyc',
    authDomain: 'kabal-xo5kyc.firebaseapp.com',
    storageBucket: 'kabal-xo5kyc.appspot.com',
  );
}
